### ISSUE TITLE
Name Text in the scaffold

### ISSUE THREAD

**Issue by oxyfalcon** [oxyfalcon/firebase_todo#7]
Provide a system to make sure that if the name exceeds the limit, then add ... to it

**Comment by dafiliks** [comment]
Hey, in what file of the project is this change needed? @oxyfalcon

**Comment by oxyfalcon** [comment]
Hey @davidfiliks . The file that needs to be focused on is the my_homepage.dart. In the scaffold, There is an app bar that has a streambuilder which takes in the Text that needs to be displayed.
What needs to be done is if the text if too big, then add triple dot eg, If name is "abcdefhg", which is too long to be fit, then it should be reduced to "abc..."

Also thank you for your interest in this repository. Feel free to use it and if there are any issues you have from your side, add it in the issues. Thanks.

**Comment by oxyfalcon** [comment]
It should be done in the way that the title in scaffold, continues to remain in the center. @davidfiliks Do you want to be assigned with this issue?

**Comment by dafiliks** [comment]
Hey, thanks for the reply. I thought this was a C/C++ issue. Unfortunately I do not know Dart so I cannot solve this problem. If you need any other issues solved that are related to C/C++ then let me know. Thanks again and I apologise.

**Comment by oxyfalcon** [comment]
Hey @davidfiliks . No problem. Thank you for checking out my repository though.

**Comment by skfareeduddin** [comment]
@oxyfalcon I proposed a solution to your issue and raised a PR. Pls review it.

**Comment by oxyfalcon** [comment]
The issue is now solved thanks @skfareeduddin Sorry for the long wait.

**Comment by oxyfalcon** [comment]
Some linting errors in your code. Please check the null safety of the code @skfareeduddin

**Comment by bonamiAkash** [comment]
Issue solve with #17
